### ISSUE TITLE
Is jquery-smooth-scroll.php released under GPLv3 ?

### ISSUE THREAD

**Issue by fu7mu4** [anandkumar/jquery-smooth-scroll#6] opened 2016-08-08 08:27 UTC
Your README said that this project is released under GPL v2 or later version 
and jquery-smooth-scroll.php of your project said that this file is released GPL v3.
So, GPL v2 is not compatible license with GPLv3, I think that the user cannot select GPL v2.
Is it right ?

**Comment by anandkumar** [comment] 2016-08-09 16:51
Thanks for letting me know! I will update the plugin and it will be released under "GPLv2 or later version".

GPLv3 is not compatible with GPLv2 but is compatible with "GPLv2 or later".

**Comment by fu7mu4** [comment] 2016-08-10 06:43
thanks for your reply. 
I'm waiting for your upgrading it.

**Comment by anandkumar** [comment] 2016-08-10 14:37
The issue is now fixed. (via https://github.com/anandkumar/jquery-smooth-scroll/commit/da6a21138710a27159ed87dc702e01f886fe18e7)

**Closed by anandkumar** 2016-08-10 14:37 UTC
